server:
  port: 8080
  context-path: /esafe
#  servlet:
#    context-path: /esafe
#    context-path: /esafe

spring:
  datasource:
    url: jdbc:mysql://39.107.251.64:3306/esafe?useSSL=false&characterEncoding=utf-8
    username: cn
    password: abc.123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    cn:
      goldlone:
        mapper: DEBUG